---
title: "Assignment 1"
---

# Assignment 1

```{r}
1 + 1
```

My first assignment has two parts.

## (c)
## Write a Custom Summary Function
```{r}
data(mtcars) 
head(mtcars) 
```
```{r}
compute_stats <- function(x) {
  
  result <- list(
    mean = mean(x),
    median = median(x),
    variance = var(x),
    IQR = IQR(x),
    minimum = min(x),
    maximum = max(x)
  )
  
  return(result)
}
```
## Applying the Function Using a Loop

```{r}
names(mtcars)
```
```{r}
numeric_cols <- sapply(mtcars, is.numeric)
numeric_names <- names(mtcars)[numeric_cols]
```

```{r}
 for (col in numeric_names) 
{  
 cat("Column:", col, "\n")
stats <- compute_stats(mtcars[[col]])
 print(stats) 
}
```
##An alternative approach with sapply and apply
```{r}
numeric_cols<-sapply(mtcars, is.numeric)
sapply(mtcars[numeric_cols], compute_stats)
```
```{r}
apply(mtcars, 2, compute_stats)
```
## (d)
```{r}
install.packages("dslabs")
```
```{r}
library(dslabs)
data(polls_us_election_2016)
head(polls_us_election_2016)
str(polls_us_election_2016)
my_first<-"Seyma"
my_birth_year<-1995
k <- (nchar(my_first) + my_birth_year) %% 15 + 8
```
```{r}
display_rows <- function(data, k) {
  if (k %% 2 == 0) {
    return(head(data, k))
  } else {
    return(tail(data, k))
  }
}
```

